apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: registry.digitalocean.com/ehsanhajian/kafka-consumer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: kafka_bootstrap_servers
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
