apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-scraper
  template:
    metadata:
      labels:
        app: temperature-scraper
    spec:
      imagePullSecrets:
      - name: do-registry
      containers:
      - name: temperature-scraper
        image: registry.digitalocean.com/ehsanhajian/temperature-scraper:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
