apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: temperature-scraper-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temperature-scraper
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
